### ISSUE TITLE
Can't Build with Actions (CI)

### ISSUE THREAD

**Issue by drogga** [drogga/android-adb-tools#3]
@nikita-yfh Can't build with GitHub Actions, please help...

I would appreciate if you can setup Actions for your repo, or build it and attach the .apk, the one already available is useless in VMOS Pro Android 9 Pie rooted Rom.

Thanks In advance ;)

**Comment by drogga** [comment]
@yakovlevegor Can you pls build this for me ?, I don't have access to Android Studio, I barely know anything, even if I did, as I don't understand the code and can't code.

**Comment by nikita-yfh** [comment]
Noroot branch in alpha stage yet, only fastboot works there.
Build: [release.zip](https://github.com/drogga/android-adb-tools/files/10126656/release.zip)
I don't know how Github actions works.

**Comment by drogga** [comment]
@nikita-yfh Thank You.
I can't make the root one work, but will try this one, even if only fastboot works, because I'm curious.
Go to the Actions tab in the repo, setup a Android CI workflow and then adjust the necessary things, because it throws a java ver. error (I think, I deleted my branch and the workflow runs, so I can show you what is the exact error) on build, that's how much I know, which is basically nothing, sorry that I can't help much.

**Comment by nikita-yfh** [comment]
> I can't make the root one work

Why?

**Comment by drogga** [comment]
Root is granted, but still:
> › adb devices

> error: cannot open '/data/local/tmp/adb.10552.log': Permission denied

Eve when I resolve that by manually creating it, I still get:
> ADB server didn't ACK
*failed to start daemon *
error: cannot connect to daemon
List of devices attached
*daemon not running. starting it now at tcp:5038 *

> Process returned 1

It doesn't want to start a\the server, finds devices, or lets me type IPs (no input field), so I can't even try to connect, other similar apps and terminalS have no problem...
ADBd and Fastboot are supposedly installed, by this: https://github.com/bavelee/ADBToolKitsInstaller, compiled app: https://apt.izzysoft.de/fdroid/index/apk/crixec.adbtoolkitsinstall

**Comment by drogga** [comment]
The alpha "noroot" build:
```
FATAL EXCEPTION: main
Process: ru.nikita.adb, PID: 2245
java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.nikita.adb/ru.nikita.adb.FastbootActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.HashMap android.hardware.usb.UsbManager.getDeviceList()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.HashMap android.hardware.usb.UsbManager.getDeviceList()' on a null object reference
	at ru.nikita.adb.FastbootActivity.updateDeviceList(Unknown Source:8)
	at ru.nikita.adb.FastbootActivity.onCreate(Unknown Source:65)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more
```

**Comment by drogga** [comment]
^ @nikita-yfh ^

**Comment by drogga** [comment]
Even if you don't reply, at least please react with a emoji on my comments, so I will at least know that you've read them ;)

**Comment by nikita-yfh** [comment]
I will fix it

**Comment by drogga** [comment]
OK thanks, but which one Root or NoRoot, or both ?
Anyway, please let me know here when that happens.

**Comment by nikita-yfh** [comment]
noroot

**Comment by nikita-yfh** [comment]
Your phone does not support USB OTG, because function getSystemService(Context.USB_SERVICE) returns null. Cause it NullPointerException. :(

**Comment by nikita-yfh** [comment]
Cause it problems with root version too :(

**Comment by nikita-yfh** [comment]
I will make popup if device does not support USB OTG

**Comment by drogga** [comment]
Well, that makes sense, since was tested in a VM, which I mentioned in the OP. I don't have anything rooted newer than A.4.3 JB, so I tested it there, the NonRoot too, either way, they (both versions\branches) shouldn't throw errors if or when there's no OTG support detected and shouldn't rely mainly on it, it should instead be focused on, and work over wireless (tcpip), since you know, A.11+ has Wireless Debugging in the Dev. Options.

**Comment by drogga** [comment]
@nikita-yfh I installed the NonRoot on Samsung Galaxy S8+ with Android 9 and it launched, but everything is greyed out, I can't click on or do anything, I also wonder why is the storage permission granted\allowed by default...

I guess it's waiting for another device to be connected via a Cable and a OTG dongle adapter, but then this statement\description from the ReadMe `Full support of OTG connection and wireless debugging` isn't that true and it's kind of pointless if it's like the Wireless ADB connection via CMD\PowerShell on Win. PC, where it first needs a USB connection and then it can be "transferred" to a Wireless (tcpip) one, even more pointless on Android 11 and newer, where you don't need to first connect it over\via USB in order to start the wireless mode, or when I want to connect a Android TV device, which can't be connected over a USB (as they are on-the-go \ as host by default) at all, but only wirelessly (can be enabled, at least since A. TV exists - form the dev. options), or via a LAN port connection, which most TVs have, but not the dongle HDMI ones.

**Comment by nikita-yfh** [comment]
> @nikita-yfh I installed the NonRoot on Samsung Galaxy S8+ with Android 9 and it launched, but everything is greyed out, I can't click on or do anything

Because app can't find any FastBoot device

**Comment by nikita-yfh** [comment]
NoRoot version supports only FastBoot yet

**Comment by drogga** [comment]
Right..., I forgot that detail > sorry, which is only a USB thing.

**Comment by drogga** [comment]
@nikita-yfh
Will you be working on the project anytime soon, and maybe try to integrate ADB in the NoRoot too, or make the Root one to not need root, since it's not actually needed for most of the things ?
There are at least 5 apps (without counting Termux) that I've used or still use some of them, which can wirelessly ADB connect and don't need any special (elevated) permissions (like root or use Shizuku for this), or fancy workarounds and coding, although they don't have as much options, or at least not all of them have a nice GUI presented in such a beautiful and simple way with buttons, without sub-menus, some are also pure shell commands execute terminal type of apps, but most importantly - they work without root, I can list some examples if you want, so you can get some ideas from them and use them as an example ?

**Comment by nikita-yfh** [comment]
I will work on NoRoot version only.
I know about this apps, but they don't support USB.

**Comment by drogga** [comment]
OK.
I think the Bugjaeger tool does, there's also a apt for Tremux: https://github.com/nohajc/termux-adb, but I just use\install the one suggested when for example you type `adb devices`, but I haven't used any of the with OTG\in USB mode, only wirelessly.

**Comment by drogga** [comment]
@nikita-yfh - OK.
I think the Bugjaeger tool does (since it's in its title and description), there's also a apt plugin or whatever is called for Tremux: https://github.com/nohajc/termux-adb, but I just use\install the one suggested when for example you type `adb devices`, but I haven't used any of them with OTG\in USB mode, only wirelessly.
